import { FONT_STACK } from '../fonts'
import { DESIGN } from '../types'

const { width, height } = DESIGN['builder-card']

const avatarRegion = {
  x: 270,
  y: 250,
  width: 540,
  height: 565,
} as const

const nameRegion = {
  x: 88,
  y: 838,
  width: 904,
  height: 100,
} as const

const titleRegion = {
  x: 126,
  y: 956,
  width: 828,
  height: 82,
} as const

/**
 * Registration map for the 1080x1350 Builder ID reverse.
 *
 * Every coordinate used by the renderer lives here. Text and the mascot stay
 * within `safeRegion`; only intentionally expendable poster decoration reaches
 * farther toward the trim.
 */
export const BUILDER_CARD_BACK_LAYOUT = {
  canvas: { width, height },
  canvasRect: { x: 0, y: 0, width, height },
  safeRegion: { left: 56, right: width - 56, top: 42, bottom: height - 42 },
  avatarRegion,
  nameRegion,
  titleRegion,
  background: {
    color: 'green-900',
    cornerBlock: {
      x: 0,
      y: 0,
      width: 274,
      height: 32,
      color: 'pink',
    },
    lowerBlock: {
      x: 0,
      y: 1318,
      width,
      height: 32,
      color: 'yellow',
    },
    outerKeyline: {
      x: 30,
      y: 30,
      width: 1020,
      height: 1290,
      radius: 28,
      strokeWidth: 6,
      color: 'cream',
    },
    innerKeyline: {
      x: 46,
      y: 46,
      width: 988,
      height: 1258,
      radius: 20,
      strokeWidth: 2,
      color: 'green-600',
    },
  },
  header: {
    accentBar: {
      x: 78,
      y: 72,
      width: 14,
      height: 108,
      color: 'pink',
    },
    eyebrow: {
      x: 116,
      baselineY: 94,
      fontFamily: FONT_STACK.text,
      fontWeight: 800,
      fontSize: 13,
      letterSpacing: 4,
      color: 'yellow',
      text: 'GOABYTE // BUILDER ID REVERSE',
    },
    event: {
      x: 114,
      baselineY: 155,
      maxWidth: 650,
      fontFamily: FONT_STACK.display,
      fontWeight: 400,
      fontSize: 49,
      minFontSize: 38,
      maxLines: 1,
      lineHeight: 52,
      color: 'cream',
      text: 'HACKER HOUSE GOA',
    },
    yearChip: {
      rect: { x: 812, y: 72, width: 170, height: 96 },
      radius: 14,
      borderWidth: 6,
      fill: 'yellow',
      stroke: 'ink',
      text: {
        centreX: 897,
        baselineY: 137,
        fontFamily: FONT_STACK.display,
        fontWeight: 400,
        fontSize: 47,
        letterSpacing: 1,
        color: 'ink',
        value: '2026',
      },
    },
    rule: {
      x: 78,
      y: 194,
      width: 924,
      height: 7,
      color: 'yellow',
    },
  },
  motifs: {
    halftone: {
      originX: 775,
      originY: 230,
      columns: 10,
      rows: 5,
      gap: 22,
      radius: 3,
      color: 'pink',
    },
    waves: {
      originX: 82,
      originY: 695,
      width: 916,
      rows: 5,
      rowGap: 23,
      amplitude: 8,
      segments: 32,
      color: 'green-600',
      lineWidth: 3,
    },
    leftPalm: {
      baseX: 104,
      baseY: 758,
      height: 228,
      lean: 55,
      color: 'yellow',
      lineWidth: 12,
    },
    rightPalm: {
      baseX: 976,
      baseY: 748,
      height: 212,
      lean: -48,
      color: 'cream-dim',
      lineWidth: 10,
    },
    sparkles: [
      { centreX: 172, centreY: 292, radius: 22, color: 'pink' },
      { centreX: 916, centreY: 360, radius: 16, color: 'yellow' },
      { centreX: 878, centreY: 706, radius: 12, color: 'cream' },
    ],
  },
  mascot: {
    avatarRegion,
    sunShadow: {
      centreX: 558,
      centreY: 519,
      radius: 242,
      color: 'pink',
    },
    sun: {
      centreX: 540,
      centreY: 497,
      radius: 224,
      rayLength: 27,
      rayCount: 20,
      fill: 'yellow',
      ink: 'ink',
      strokeWidth: 9,
    },
    shadow: {
      body: { x: 409, y: 373, width: 300, height: 382 },
      bodyRadius: 140,
      leftFoot: { x: 420, y: 704, width: 116, height: 98 },
      rightFoot: { x: 579, y: 704, width: 116, height: 98 },
      footRadius: 42,
      color: 'pink',
    },
    backpack: {
      rect: { x: 316, y: 450, width: 112, height: 204 },
      radius: 42,
      fill: 'pink',
      stroke: 'ink',
      borderWidth: 12,
      seam: {
        x1: 344,
        y1: 496,
        x2: 344,
        y2: 610,
        color: 'ink',
        lineWidth: 7,
      },
    },
    arms: [
      {
        start: { x: 410, y: 477 },
        control1: { x: 359, y: 492 },
        control2: { x: 330, y: 548 },
        end: { x: 350, y: 615 },
        glove: { centreX: 354, centreY: 627, radius: 29 },
      },
      {
        start: { x: 670, y: 479 },
        control1: { x: 728, y: 498 },
        control2: { x: 748, y: 548 },
        end: { x: 720, y: 606 },
        glove: { centreX: 716, centreY: 619, radius: 29 },
      },
    ],
    armStyle: {
      outerWidth: 58,
      innerWidth: 34,
      outerColor: 'ink',
      innerColor: 'cream',
      gloveFill: 'cream',
      gloveStroke: 'ink',
      gloveBorderWidth: 10,
    },
    body: {
      rect: { x: 390, y: 354, width: 300, height: 382 },
      radius: 140,
      fill: 'cream',
      stroke: 'ink',
      borderWidth: 14,
    },
    feet: [
      { x: 401, y: 686, width: 116, height: 105 },
      { x: 560, y: 686, width: 116, height: 105 },
    ],
    footStyle: {
      radius: 42,
      fill: 'cream',
      stroke: 'ink',
      borderWidth: 14,
    },
    helmetBand: {
      rect: { x: 411, y: 375, width: 258, height: 190 },
      radius: 86,
      fill: 'pink',
      stroke: 'ink',
      borderWidth: 11,
    },
    visor: {
      rect: { x: 429, y: 392, width: 224, height: 145 },
      radius: 64,
      fill: 'green-700',
      stroke: 'ink',
      borderWidth: 10,
      highlight: {
        rect: { x: 468, y: 420, width: 83, height: 24 },
        radius: 12,
        color: 'cream',
      },
      glint: {
        centreX: 577,
        centreY: 431,
        radius: 10,
        color: 'yellow',
      },
    },
    console: {
      rect: { x: 447, y: 572, width: 186, height: 96 },
      radius: 23,
      fill: 'green-900',
      stroke: 'ink',
      borderWidth: 9,
      screen: {
        rect: { x: 469, y: 593, width: 92, height: 40 },
        radius: 8,
        color: 'green-600',
      },
      controls: [
        { centreX: 588, centreY: 604, radius: 9, color: 'yellow' },
        { centreX: 608, centreY: 625, radius: 9, color: 'pink' },
      ],
      codeMark: {
        left: {
          start: { x: 486, y: 606 },
          middle: { x: 477, y: 613 },
          end: { x: 486, y: 620 },
        },
        slash: { start: { x: 503, y: 601 }, end: { x: 495, y: 625 } },
        right: {
          start: { x: 514, y: 606 },
          middle: { x: 523, y: 613 },
          end: { x: 514, y: 620 },
        },
        color: 'cream',
        lineWidth: 5,
      },
    },
    patch: {
      centreX: 648,
      centreY: 609,
      radius: 23,
      fill: 'yellow',
      stroke: 'ink',
      borderWidth: 7,
      text: {
        centreX: 648,
        baselineY: 615,
        fontFamily: FONT_STACK.text,
        fontWeight: 800,
        fontSize: 13,
        letterSpacing: 1,
        color: 'ink',
        value: 'GOA',
      },
    },
  },
  identity: {
    label: {
      centreX: 540,
      baselineY: 842,
      fontFamily: FONT_STACK.text,
      fontWeight: 800,
      fontSize: 14,
      letterSpacing: 5,
      color: 'pink',
      text: 'CREW BUILDER // IDENTIFIED',
    },
    name: {
      region: nameRegion,
      centreX: 540,
      topY: 844,
      maxWidth: 904,
      fontFamily: FONT_STACK.display,
      fontWeight: 400,
      fontSize: 86,
      minFontSize: 50,
      maxLines: 1,
      lineHeight: 92,
      color: 'cream',
      fallback: 'BUILDER',
    },
    title: {
      region: titleRegion,
      box: titleRegion,
      radius: 18,
      borderWidth: 6,
      fill: 'yellow',
      stroke: 'ink',
      centreX: 540,
      topY: 968,
      maxWidth: 744,
      fontFamily: FONT_STACK.text,
      fontWeight: 800,
      fontSize: 34,
      minFontSize: 20,
      maxLines: 1,
      lineHeight: 48,
      letterSpacing: 2,
      color: 'ink',
      fallback: 'BUILDER',
    },
  },
  campaign: {
    divider: {
      left: { x: 172, y: 1092, width: 132, height: 5 },
      right: { x: 776, y: 1092, width: 132, height: 5 },
      color: 'pink',
    },
    buildLine: {
      centreX: 540,
      baselineY: 1102,
      fontFamily: FONT_STACK.text,
      fontWeight: 800,
      fontSize: 27,
      letterSpacing: 4,
      color: 'yellow',
      text: 'BUILD · SHIP · GOA',
    },
    hashtag: {
      centreX: 540,
      baselineY: 1182,
      fontFamily: FONT_STACK.display,
      fontWeight: 400,
      fontSize: 53,
      letterSpacing: 1,
      color: 'cream',
      text: '#FrameInGoa',
    },
  },
  footer: {
    plaque: {
      x: 76,
      y: 1226,
      width: 928,
      height: 65,
      radius: 12,
      borderWidth: 5,
      fill: 'pink',
      stroke: 'ink',
    },
    text: {
      centreX: 540,
      baselineY: 1268,
      fontFamily: FONT_STACK.text,
      fontWeight: 800,
      fontSize: 15,
      letterSpacing: 3,
      color: 'ink',
      value: 'GOABYTE BUILDER STUDIO · GOA, INDIA',
    },
  },
} as const

/** Short alias matching the existing front renderer's `CARD_LAYOUT` naming. */
export const CARD_BACK_LAYOUT = BUILDER_CARD_BACK_LAYOUT
